name: github-action-checkout

on: push

jobs:
    first_check:
      runs-on: ubuntu-latest
      steps:
      - name: initiate a checkout
        uses: actions/checkout@v4

       - name: list all files 
         run: ls -ltra

      - name: cat file 
        run: cat README.md
              
            